In [41]:
import pandas as pd
import json

In [61]:
df = pd.read_csv('cleaned_data.csv')
df.head()

,round_winner,player_1_team_name,player_1_name,player_1_team_num,player_1_kills_total,player_1_deaths_total,player_1_has_defuser,player_1_has_helmet,player_1_armor_value,player_1_current_equip_value,...,player_10_CZ75-Auto,player_10_Desert Eagle,player_10_R8 Revolver,player_10_Dual Berettas,player_10_Smoke Grenade,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade
0,1,G2 Esports,NiKo,0,1,1,0,0,0.0,700.0,...,0,0,0,0,1,0,1,1,0,0
1,1,G2 Esports,NiKo,0,1,2,0,1,100.0,4100.0,...,0,0,0,0,1,1,1,1,0,0
2,0,G2 Esports,NiKo,0,1,3,0,1,100.0,5100.0,...,0,0,0,0,1,1,0,1,0,0
3,1,G2 Esports,NiKo,0,3,4,0,1,100.0,2800.0,...,0,0,0,0,1,1,0,1,0,0
4,1,G2 Esports,NiKo,0,4,5,0,0,0.0,200.0,...,0,0,0,0,1,1,1,1,0,0

In [62]:
player_names = []
for i in range(1, 11):
    player_name_col = f'player_{i}_name'
    if player_name_col in df.columns:
        player_names.append(df[player_name_col])
all_player_names = pd.concat(player_names)
unique_player_names = all_player_names.unique()
print("Unique Player Names:", unique_player_names)

Unique Player Names: ['NiKo' 'Lucky' 'HooXi' 'doc' 'drg' 'device' 'Skullz' 'kye' 'hazr'
 'iDISBALANCE' 'glowiing' 'magnojez' 'zorte' 'Vexite' 'm0NESY' 'maxster'
 'r1nkle' 'Cryptic' 'cJ-dA-K1nG' 'Ax1Le' 'Aleksib' 'hallzerk' 'Grim'
 'nexa' 'Snax' 'Calyx' 'w0nderful' 'Magisk' 'dupreeh' 'broky' 'frozen'
 'ropz' 'Woro2k' 'jL' 'b1t' 'chayJESUS' 'INS' 'xKacpersky' 'bibu' 'Aaron'
 'MATYS' 'afro' 'kyuubii' 'gla1ve' 'FalleN' 'buda' 'karrigan' 'chelo'
 'huNter' 'YEKINDAR' 'NAF' 'skullz' 'westmelon' 'Starry' 'slaxz-'
 'malbsMd' 'iM' 'volt' 'aNdu' 'Jyo' 'Ryujin' 'nicoodoz' 'Krimbo' 'NertZ'
 'kyxsan' 'noway' 'HEN1' 'naz' 'shz' 'cadiaN' 'dexter' 'kRaSnaL'
 'NickelBack' 'smooya' 'KSCERATO' 'Gizmy' 'Brollan' 'torzsi' 'xertioN'
 'Jimpphat' 'Twistzz' 'STYKO' 'CacaNito' 'KaiR0N-' 'nafany' 'floppy' 'JT'
 'EliGE' 'Queenix' 'JUST' 'n1ssim' 'zont1x' 'sh1ro' 'fame' 'lattykk'
 'neaLaN' '1eeR' 'SHOCK' 'AJTT' 'CLASIA' 'lux' 'nython' 'dav1deuS'
 'venomzera' 'snow' 'nqz' 'CRUC1AL' 'Surreal' 'FL1T' '910' 'Senzu' 'Kaze'
 'mir' 'Jame' 'Spinx' 'Ex3rcice' 'Djoko' 'Graviti' 'MartinezSa'
 'HUASOPEEK' 'jabbi' 'Magnojez' 'Liazz' 'PwnAlone' 'alex' 'Boombl4'
 'electroNic' 'Nodios' 'Patti' 'woxic' 'MAJ3R' 'maden' 'SunPayus' 'Snappi'
 'Porya' 'KRiMZ' 'd1Ledez' 'bodyy' 'Perfecto' 'XANTARES' 'rain' 'TeSeS'
 'Swisher' 'k0nfig' 'electronic' 'JDC' 'tabseN' 'felps' 'VINI' 'ponter'
 'aliStair' 'tN1R' 'sdy' 'siuhy' 'sense' 'salazar' 'fr3nd' 'adamS'
 'chopper' 'magixx' 'oskar' 'BluePho3nix' 'junior' 'biguzera' 'AZUWU'
 'donk' 'Mzinho' 'Techno' 'JamYoung' 'ZywOo' 'stavn' 'yuurih' 'damyo'
 'clax' 'syrsoN' 'FaNg' 'DemQQ' 'dgl' 'Ciocardau' 'HObbit' 'z4kr' 'Jee'
 'reck' 's1n' 'es3tag' 'isak' 'SENER1' 'buster' 'sjuush' 'Noktse' 'meyern'
 'shalfey' 'Ryu' 'br0' 'nawwk' 'danistzz' 'Wicadia' 'mzinho' 'riskyb0b'
 'beastik' 'Jeorge' 'hardzao' 'MiGHTYMAX' 'cej0t' 'n0rb3r7' 'Mercury'
 's1ren' 'prosus' 'freshie' 'nosraC' 'kraghen' 'arT' 'Goofy' 'dycha'
 'gxx-' 'tomaszin' 'decenty' 'iDk' 'pesadelo' 'SELLTER' 'toao' 'kauez'
 'Xant3r' 'NEOFRAG' 'nicks' 'zdr' 'flameZ' 'Maka' 'togs' 'gafolo' 'BRACE'
 'Kylar' 'BOROS' 'seized' 'EmiliaQAQ' 'headtr1ck' 'REZ' 'bLitz'
 'juanflatroo' 'rigoN' 'luchov' 'jkaem' 'dav1g' 'zevy' 'coldzera' 'advent'
 'mezii' 'apEX' 'dgt' 'sl3nd' 'f4stzin' 'naitte' 'mopoz' 'khaN' 'pz'
 'd4rty' 'hades' 'sinnopsyy' 'cass1n' 'Tuurtle' 'matios' 'FL4MUS' 'max'
 'Staehr' 'ex1st' 'ADDICT' 'WOOD7' 'Kraghen' 'Demho' 'stadodo' 'Lucaozy'
 'Coldzera' 'rdnzao' 'bajmi']

In [63]:
len(unique_player_names)

274

In [64]:
player_team_names = []
for i in range(1, 11):
    player_team_col = f'player_{i}_team_name'
    if player_team_col in df.columns:
        player_team_names.append(df[player_team_col])
all_player_team_names = pd.concat(player_team_names)
unique_player_team_names = all_player_team_names.unique()
print("Unique Player Team Names:", unique_player_team_names)

Unique Player Team Names: ['G2 Esports' '3DMAX' 'Sharks' 'Astralis' 'Team Liquid' 'FURIA'
 'Bad News Kangaroos' '9 Pandas' 'BetBoom' 'FlyQuest' 'Ninjas In Pyjamas'
 'BOSS' 'Nouns Esports' 'Cloud9' 'Natus Vincere' 'Complexity'
 'GamerLegion' 'Eternal Fire' 'Team Falcons' 'FaZe Clan' 'Monte' 'Fluxo'
 'PERA Esports' 'Fnatic' 'ENCE' '9z' 'Lynn Vision Gaming' 'M80' '1WIN'
 'HEROIC' 'BIG' 'Heroic' 'Imperial Esports' 'BESTIA' 'inSanitY' 'FORZE'
 'MOUZ' 'Apeks' 'ECSTATIC' 'Movistar KOI' 'paiN Gaming' 'Team Spirit'
 'Virtus.pro' 'Nemiga' 'SINNERS' 'RED Canids' 'Endpoint' 'The MongolZ'
 'TYLOO' 'Virtus.Pro' 'Team Vitality' 'ODDIK' 'Enterprise esports' 'Boss'
 'Guild Eagles']

REMEMBER THAT NAVI CAN WAS FOUND IN DEMOS AS NAVI, NAVI- AND NATUS VINCERE
Virtus.pro can be found as Virtus.proVP 
Team Liquid is also found as Liquid

In [65]:
len(unique_player_team_names)

55

In [66]:
with open('players_stats.json') as file:
    players_stats = json.load(file)

with open('teams_stats.json') as file:
    teams_stats = json.load(file)

In [67]:
json_player_names = list(players_stats.keys())
json_team_names = list(teams_stats.keys())

In [49]:
print("Number of players in JSON:", len(json_player_names))
print("Number of teams in JSON:", len(json_team_names))

Number of players in JSON: 288
Number of teams in JSON: 56

In [50]:
matching_player_names = [name for name in json_player_names if name.lower() in (n.lower() for n in unique_player_names)]
print(f"Matching Player Names: {len(matching_player_names)} out of {len(json_player_names)}")
print("Names:", matching_player_names)

Matching Player Names: 268 out of 288
Names: ['karrigan', 'rain', 'frozen', 'ropz', 'broky', 'Aleksib', 'iM', 'b1t', 'jL', 'w0nderful', 'Brollan', 'siuhy', 'torzsi', 'Jimpphat', 'xertioN', 'chopper', 'sh1ro', 'magixx', 'zont1x', 'donk', 'NiKo', 'huNter', 'nexa', 'HooXi', 'm0NESY', 'apEX', 'ZywOo', 'flameZ', 'Spinx', 'mezii', 'MAJ3R', 'XANTARES', 'woxic', 'Calyx', 'Wicadia', 'device', 'stavn', 'br0', 'jabbi', 'Staehr', 'electroNic', 'FL1T', 'Jame', 'n0rb3r7', 'fame', 'NertZ', 'TeSeS', 'nicoodoz', 'sjuush', 'kyxsan', 'EliGE', 'JT', 'floppy', 'hallzerk', 'Grim', 'Snappi', 'dupreeh', 'Magisk', 'Maden', 'SunPayus', 'biguzera', 'nqz', 'kauez', 'snow', 'lux', 'gla1ve', 'Goofy', 'dycha', 'hades', 'Kylar', 'cadiaN', 'NAF', 'Twistzz', 'YEKINDAR', 'skullz', 'HEN1', 'felps', 'VINI', 'decenty', 'noway', 'bLitz', 'Techno', 'Senzu', 'mzinho', '910', 'FalleN', 'chelo', 'yuurih', 'KSCERATO', 'dexter', 'Liazz', 'aliStair', 'INS', 'Vexite', 'Nodios', 'Patti', 'Queenix', 'kraghen', 'salazar', 'Woro2k', 'DemQQ', 'kRaSnaL', 'ryu', 'Gizmy', 'zorte', 'nafany', 's1ren', 'KaiR0N-', 'Magnojez', 'Snax', 'volt', 'sl3nd', 'aNdu', 'jkaem', 'nawwk', 'sense', 'CacaNito', 'tabseN', 'syrsoN', 'JDC', 'prosus', 'Krimbo', 'malbsMd', 'slaxz-', 'Swisher', 'reck', 's1n', 'Maka', 'Lucky', 'Djoko', 'Ex3rcice', 'Graviti', 'drg', 'togs', 'gafolo', 'rdnzao', 'doc', 'BRACE', 'hazr', 'pz', 'damyo', 'ADDICT', 'seized', 'clax', 'iDISBALANCE', 'glowiing', 'd1Ledez', 'alex', 'REZ', 'r1nkle', 'isak', 'maxster', 'PwnAlone', 'Cryptic', 'FaNg', 'freshie', 'd4rty', 'cJ-dA-K1nG', 'junior', 'nosraC', 'CLASIA', 'Jeorge', 'Boombl4', 'Ax1Le', 'arT', 'Lucaozy', 'zevy', 'chayJESUS', 'nicks', 'Aaron', 'Ciocardau', 'Porya', 'Bibu', 'DGL', 'KRIMZ', 'bodyy', 'afro', 'kyuubii', 'MATYS', 'max', 'dgt', 'buda', 'MartinezSa', 'HUASOPEEK', 'Jee', 'Westmelon', 'z4kr', 'Starry', 'EmiliaQAQ', 'neaLaN', 'buster', 'Jyo', 'Ryujin', 'lattykk', 'Noktse', 'meyern', 'luchov', 'naz', 'tomaszin', 'iDk', 'shz', 'pesadelo', 'f4stzin', 'cass1n', 'SELLTER', 'NickelBack', 'tN1R', 'shalfey', 'smooya', 'JUST', 'mopoz', 'stadodo', 'dav1g', 'adamS', 'Xant3r', '1eeR', 'riskyb0b', 'khaN', 'FL4MUS', 'oskar', 'beastik', 'SHOCK', 'AJTT', 'NEOFRAG', 'coldzera', 'hardzao', 'nython', 'dav1deuS', 'venomzera', 'CRUC1AL', 'MiGHTYMAX', 'Surreal', 'AZUWU', 'cej0t', 'advent', 'kaze', 'JamYoung', 'Mercury', 'zdr', 'WOOD7', 'ponter', 'Tuurtle', 'naitte', 'matios', 'TOAO', 'Demho', 'fr3nd', 'bajmi', 'ex1st', 'rigoN', 'SENER1', 'juanflatroo', 'sinnopsyy', 'gxx-', 'kye', 'xKacpersky', 'STYKO', 'n1ssim', 'mir', 'Perfecto', 'k0nfig', 'sdy', 'BluePho3nix', 'HObbit', 'es3tag', 'danistzz', 'BOROS', 'headtr1ck']

9Pandas Esports -> 9 Pandas | EcstaticCS2 -> ECSTATIC | 9z Globant -> 9z

In [51]:
matching_team_names = [name for name in json_team_names if name.lower() in (n.lower() for n in unique_player_team_names)]
print(f"Matching Team Names: {len(matching_team_names)} out of {len(json_team_names)}")
print("Names:", matching_team_names)
missing_team_names = [name for name in unique_player_team_names if name.lower() not in (n.lower() for n in matching_team_names)]
print(f"Missing Team Names: {missing_team_names}")

Matching Team Names: 52 out of 56
Names: ['FaZe Clan', 'Natus Vincere', 'MOUZ', 'Team Spirit', 'G2 Esports', 'Team Vitality', 'Eternal Fire', 'Astralis', 'Virtus.pro', 'Heroic', 'Complexity', 'Team Falcons', 'paiN Gaming', 'ENCE', 'Team Liquid', 'Imperial Esports', 'The MongolZ', 'FURIA', 'FlyQuest', 'Monte', 'BetBoom', 'GamerLegion', 'Apeks', 'BIG', 'M80', 'Bad News Kangaroos', 'Sharks', '3DMAX', '9 Pandas', 'Ninjas In Pyjamas', 'BOSS', 'Nouns Esports', 'Cloud9', 'Fluxo', 'PERA Esports', 'Fnatic', '9z', 'Lynn Vision Gaming', '1WIN', 'BESTIA', 'inSanitY', 'FORZE', 'ECSTATIC', 'Movistar KOI', 'Nemiga', 'SINNERS', 'RED Canids', 'Endpoint', 'TYLOO', 'ODDIK', 'Enterprise esports', 'Guild Eagles']
Missing Team Names: []

In [52]:
missing_player_names = [name for name in unique_player_names if name.lower() not in (n.lower() for n in matching_player_names)]
print(f"Missing Player Names: {missing_player_names}")

Missing Player Names: []

In [68]:
def get_unique_teams(row):
    teams = {row[f'player_{i}_team_name'] for i in range(1, 11) if f'player_{i}_team_name' in row}
    return list(teams)

df['unique_teams'] = df.apply(get_unique_teams, axis=1)

In [69]:
df.head()

,round_winner,player_1_team_name,player_1_name,player_1_team_num,player_1_kills_total,player_1_deaths_total,player_1_has_defuser,player_1_has_helmet,player_1_armor_value,player_1_current_equip_value,...,player_10_Desert Eagle,player_10_R8 Revolver,player_10_Dual Berettas,player_10_Smoke Grenade,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade,unique_teams
0,1,G2 Esports,NiKo,0,1,1,0,0,0.0,700.0,...,0,0,0,1,0,1,1,0,0,"[G2 Esports, 3DMAX]"
1,1,G2 Esports,NiKo,0,1,2,0,1,100.0,4100.0,...,0,0,0,1,1,1,1,0,0,"[G2 Esports, 3DMAX]"
2,0,G2 Esports,NiKo,0,1,3,0,1,100.0,5100.0,...,0,0,0,1,1,0,1,0,0,"[G2 Esports, 3DMAX]"
3,1,G2 Esports,NiKo,0,3,4,0,1,100.0,2800.0,...,0,0,0,1,1,0,1,0,0,"[G2 Esports, 3DMAX]"
4,1,G2 Esports,NiKo,0,4,5,0,0,0.0,200.0,...,0,0,0,1,1,1,1,0,0,"[G2 Esports, 3DMAX]"

In [70]:
def team_stats_lookup(teams, stat):
    return [teams_stats.get(team, {}).get(stat, 'NA') for team in teams]

In [71]:
df['team_1_position'] = df['unique_teams'].apply(lambda teams: team_stats_lookup(teams, 'position')[0] if len(teams) > 0 else 'NA')
df['team_1_win_percentage'] = df['unique_teams'].apply(lambda teams: team_stats_lookup(teams, 'win_percentage')[0] if len(teams) > 0 else 'NA')

In [72]:
df['team_2_position'] = df['unique_teams'].apply(lambda teams: team_stats_lookup(teams, 'position')[1] if len(teams) > 1 else 'NA')
df['team_2_win_percentage'] = df['unique_teams'].apply(lambda teams: team_stats_lookup(teams, 'win_percentage')[1] if len(teams) > 1 else 'NA')

In [73]:
df.head()

,round_winner,player_1_team_name,player_1_name,player_1_team_num,player_1_kills_total,player_1_deaths_total,player_1_has_defuser,player_1_has_helmet,player_1_armor_value,player_1_current_equip_value,...,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade,unique_teams,team_1_position,team_1_win_percentage,team_2_position,team_2_win_percentage
0,1,G2 Esports,NiKo,0,1,1,0,0,0.0,700.0,...,0,1,1,0,0,"[G2 Esports, 3DMAX]",5,66.7,30,58.1
1,1,G2 Esports,NiKo,0,1,2,0,1,100.0,4100.0,...,1,1,1,0,0,"[G2 Esports, 3DMAX]",5,66.7,30,58.1
2,0,G2 Esports,NiKo,0,1,3,0,1,100.0,5100.0,...,1,0,1,0,0,"[G2 Esports, 3DMAX]",5,66.7,30,58.1
3,1,G2 Esports,NiKo,0,3,4,0,1,100.0,2800.0,...,1,0,1,0,0,"[G2 Esports, 3DMAX]",5,66.7,30,58.1
4,1,G2 Esports,NiKo,0,4,5,0,0,0.0,200.0,...,1,1,1,0,0,"[G2 Esports, 3DMAX]",5,66.7,30,58.1

In [74]:
insert_pos = df.columns.get_loc('round_winner') + 1

team_stats_cols = ['team_1_position', 'team_1_win_percentage', 'team_2_position', 'team_2_win_percentage']

for col in reversed(team_stats_cols):
    df.insert(insert_pos, col, df.pop(col))

In [75]:
df.head()

,round_winner,team_1_position,team_1_win_percentage,team_2_position,team_2_win_percentage,player_1_team_name,player_1_name,player_1_team_num,player_1_kills_total,player_1_deaths_total,...,player_10_Desert Eagle,player_10_R8 Revolver,player_10_Dual Berettas,player_10_Smoke Grenade,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade,unique_teams
0,1,5,66.7,30,58.1,G2 Esports,NiKo,0,1,1,...,0,0,0,1,0,1,1,0,0,"[G2 Esports, 3DMAX]"
1,1,5,66.7,30,58.1,G2 Esports,NiKo,0,1,2,...,0,0,0,1,1,1,1,0,0,"[G2 Esports, 3DMAX]"
2,0,5,66.7,30,58.1,G2 Esports,NiKo,0,1,3,...,0,0,0,1,1,0,1,0,0,"[G2 Esports, 3DMAX]"
3,1,5,66.7,30,58.1,G2 Esports,NiKo,0,3,4,...,0,0,0,1,1,0,1,0,0,"[G2 Esports, 3DMAX]"
4,1,5,66.7,30,58.1,G2 Esports,NiKo,0,4,5,...,0,0,0,1,1,1,1,0,0,"[G2 Esports, 3DMAX]"

In [76]:
df.drop(columns=['unique_teams'], inplace=True)

In [77]:
df.head()

,round_winner,team_1_position,team_1_win_percentage,team_2_position,team_2_win_percentage,player_1_team_name,player_1_name,player_1_team_num,player_1_kills_total,player_1_deaths_total,...,player_10_CZ75-Auto,player_10_Desert Eagle,player_10_R8 Revolver,player_10_Dual Berettas,player_10_Smoke Grenade,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade
0,1,5,66.7,30,58.1,G2 Esports,NiKo,0,1,1,...,0,0,0,0,1,0,1,1,0,0
1,1,5,66.7,30,58.1,G2 Esports,NiKo,0,1,2,...,0,0,0,0,1,1,1,1,0,0
2,0,5,66.7,30,58.1,G2 Esports,NiKo,0,1,3,...,0,0,0,0,1,1,0,1,0,0
3,1,5,66.7,30,58.1,G2 Esports,NiKo,0,3,4,...,0,0,0,0,1,1,0,1,0,0
4,1,5,66.7,30,58.1,G2 Esports,NiKo,0,4,5,...,0,0,0,0,1,1,1,1,0,0

In [78]:
all_new_columns = {}

for i in range(1, 11):
    if f'player_{i}_name' in df.columns:
        new_columns_df = pd.DataFrame(index=df.index)
        
        new_columns_df[f'player_{i}_rating'] = df[f'player_{i}_name'].map(lambda x: players_stats.get(x, {}).get('Rating', 'NA'))
        new_columns_df[f'player_{i}_kills_per_round'] = df[f'player_{i}_name'].map(lambda x: players_stats.get(x, {}).get('Kills Per Round', 'NA'))
        new_columns_df[f'player_{i}_headshots'] = df[f'player_{i}_name'].map(lambda x: players_stats.get(x, {}).get('Headshots', 'NA'))
        new_columns_df[f'player_{i}_deaths_per_round'] = df[f'player_{i}_name'].map(lambda x: players_stats.get(x, {}).get('Deaths Per Round', 'NA'))
        new_columns_df[f'player_{i}_rounds_contributed'] = df[f'player_{i}_name'].map(lambda x: players_stats.get(x, {}).get('Rounds Contributed', 'NA'))
        
        all_new_columns[f'player_{i}_name'] = new_columns_df

In [79]:
for key, value in all_new_columns.items():
    insert_pos = df.columns.get_loc(key) + 1
    df = pd.concat([df.iloc[:, :insert_pos], value, df.iloc[:, insert_pos:]], axis=1)

In [80]:
df.head()

,round_winner,team_1_position,team_1_win_percentage,team_2_position,team_2_win_percentage,player_1_team_name,player_1_name,player_1_rating,player_1_kills_per_round,player_1_headshots,...,player_10_CZ75-Auto,player_10_Desert Eagle,player_10_R8 Revolver,player_10_Dual Berettas,player_10_Smoke Grenade,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade
0,1,5,66.7,30,58.1,G2 Esports,NiKo,1.18,0.72,51.8,...,0,0,0,0,1,0,1,1,0,0
1,1,5,66.7,30,58.1,G2 Esports,NiKo,1.18,0.72,51.8,...,0,0,0,0,1,1,1,1,0,0
2,0,5,66.7,30,58.1,G2 Esports,NiKo,1.18,0.72,51.8,...,0,0,0,0,1,1,0,1,0,0
3,1,5,66.7,30,58.1,G2 Esports,NiKo,1.18,0.72,51.8,...,0,0,0,0,1,1,0,1,0,0
4,1,5,66.7,30,58.1,G2 Esports,NiKo,1.18,0.72,51.8,...,0,0,0,0,1,1,1,1,0,0

In [81]:
df.to_csv('cleaned_data_with_stats.csv', index=False)