In [2]:
import pandas as pd
import json

In [4]:
df = pd.read_csv('../data/cleaned_rounds_data.csv')
df.head()

,round_winner,player_1_team_name,player_1_name,player_1_team_num,player_1_kills_total,player_1_deaths_total,player_1_has_defuser,player_1_has_helmet,player_1_armor_value,player_1_current_equip_value,...,player_10_CZ75-Auto,player_10_Desert Eagle,player_10_R8 Revolver,player_10_Dual Berettas,player_10_Smoke Grenade,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade
0,1,G2 Esports,NiKo,0,1.0,1.0,0,0,0.0,700.0,...,0,0,0,0,1,0,1,1,0,0
1,1,G2 Esports,NiKo,0,1.0,2.0,0,1,100.0,4100.0,...,0,0,0,0,1,1,1,1,0,0
2,0,G2 Esports,NiKo,0,1.0,3.0,0,1,100.0,5100.0,...,0,0,0,0,1,1,0,1,0,0
3,1,G2 Esports,NiKo,0,3.0,4.0,0,1,100.0,2800.0,...,0,0,0,0,1,1,0,1,0,0
4,1,G2 Esports,NiKo,0,4.0,5.0,0,0,0.0,200.0,...,0,0,0,0,1,1,1,1,0,0

In [5]:
def get_unique_teams(row):
    teams = {row[f'player_{i}_team_name'] for i in range(1, 11) if f'player_{i}_team_name' in row}
    return list(teams)

df['unique_teams'] = df.apply(get_unique_teams, axis=1)

In [6]:
df.head()

,round_winner,player_1_team_name,player_1_name,player_1_team_num,player_1_kills_total,player_1_deaths_total,player_1_has_defuser,player_1_has_helmet,player_1_armor_value,player_1_current_equip_value,...,player_10_Desert Eagle,player_10_R8 Revolver,player_10_Dual Berettas,player_10_Smoke Grenade,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade,unique_teams
0,1,G2 Esports,NiKo,0,1.0,1.0,0,0,0.0,700.0,...,0,0,0,1,0,1,1,0,0,"[G2 Esports, 3DMAX]"
1,1,G2 Esports,NiKo,0,1.0,2.0,0,1,100.0,4100.0,...,0,0,0,1,1,1,1,0,0,"[G2 Esports, 3DMAX]"
2,0,G2 Esports,NiKo,0,1.0,3.0,0,1,100.0,5100.0,...,0,0,0,1,1,0,1,0,0,"[G2 Esports, 3DMAX]"
3,1,G2 Esports,NiKo,0,3.0,4.0,0,1,100.0,2800.0,...,0,0,0,1,1,0,1,0,0,"[G2 Esports, 3DMAX]"
4,1,G2 Esports,NiKo,0,4.0,5.0,0,0,0.0,200.0,...,0,0,0,1,1,1,1,0,0,"[G2 Esports, 3DMAX]"

In [7]:
with open('../data/players_stats.json') as file:
    players_stats = json.load(file)

with open('../data/teams_stats.json') as file:
    teams_stats = json.load(file)

teams_stats = {k.lower(): v for k, v in teams_stats.items()}
players_stats = {k.lower(): v for k, v in players_stats.items()}

In [8]:
def team_stats_lookup(teams, stat):
    return [teams_stats.get(team.lower(), {}).get(stat, 'NA') for team in teams]

In [9]:
df['team_1_position'] = df['unique_teams'].apply(lambda teams: team_stats_lookup(teams, 'position')[0] if len(teams) > 0 else 'NA')
df['team_1_win_percentage'] = df['unique_teams'].apply(lambda teams: team_stats_lookup(teams, 'win_percentage')[0] if len(teams) > 0 else 'NA')
df['team_2_position'] = df['unique_teams'].apply(lambda teams: team_stats_lookup(teams, 'position')[1] if len(teams) > 0 else 'NA')
df['team_2_win_percentage'] = df['unique_teams'].apply(lambda teams: team_stats_lookup(teams, 'win_percentage')[1] if len(teams) > 0 else 'NA')

In [10]:
df.head()

,round_winner,player_1_team_name,player_1_name,player_1_team_num,player_1_kills_total,player_1_deaths_total,player_1_has_defuser,player_1_has_helmet,player_1_armor_value,player_1_current_equip_value,...,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade,unique_teams,team_1_position,team_1_win_percentage,team_2_position,team_2_win_percentage
0,1,G2 Esports,NiKo,0,1.0,1.0,0,0,0.0,700.0,...,0,1,1,0,0,"[G2 Esports, 3DMAX]",5,66.7,30,58.1
1,1,G2 Esports,NiKo,0,1.0,2.0,0,1,100.0,4100.0,...,1,1,1,0,0,"[G2 Esports, 3DMAX]",5,66.7,30,58.1
2,0,G2 Esports,NiKo,0,1.0,3.0,0,1,100.0,5100.0,...,1,0,1,0,0,"[G2 Esports, 3DMAX]",5,66.7,30,58.1
3,1,G2 Esports,NiKo,0,3.0,4.0,0,1,100.0,2800.0,...,1,0,1,0,0,"[G2 Esports, 3DMAX]",5,66.7,30,58.1
4,1,G2 Esports,NiKo,0,4.0,5.0,0,0,0.0,200.0,...,1,1,1,0,0,"[G2 Esports, 3DMAX]",5,66.7,30,58.1

In [11]:
insert_pos = df.columns.get_loc('round_winner') + 1

team_stats_cols = ['team_1_position', 'team_1_win_percentage', 'team_2_position', 'team_2_win_percentage']

for col in reversed(team_stats_cols):
    df.insert(insert_pos, col, df.pop(col))

In [12]:
df.head()

,round_winner,team_1_position,team_1_win_percentage,team_2_position,team_2_win_percentage,player_1_team_name,player_1_name,player_1_team_num,player_1_kills_total,player_1_deaths_total,...,player_10_Desert Eagle,player_10_R8 Revolver,player_10_Dual Berettas,player_10_Smoke Grenade,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade,unique_teams
0,1,5,66.7,30,58.1,G2 Esports,NiKo,0,1.0,1.0,...,0,0,0,1,0,1,1,0,0,"[G2 Esports, 3DMAX]"
1,1,5,66.7,30,58.1,G2 Esports,NiKo,0,1.0,2.0,...,0,0,0,1,1,1,1,0,0,"[G2 Esports, 3DMAX]"
2,0,5,66.7,30,58.1,G2 Esports,NiKo,0,1.0,3.0,...,0,0,0,1,1,0,1,0,0,"[G2 Esports, 3DMAX]"
3,1,5,66.7,30,58.1,G2 Esports,NiKo,0,3.0,4.0,...,0,0,0,1,1,0,1,0,0,"[G2 Esports, 3DMAX]"
4,1,5,66.7,30,58.1,G2 Esports,NiKo,0,4.0,5.0,...,0,0,0,1,1,1,1,0,0,"[G2 Esports, 3DMAX]"

In [13]:
df.drop(columns=['unique_teams'], inplace=True)

In [14]:
df.head()

,round_winner,team_1_position,team_1_win_percentage,team_2_position,team_2_win_percentage,player_1_team_name,player_1_name,player_1_team_num,player_1_kills_total,player_1_deaths_total,...,player_10_CZ75-Auto,player_10_Desert Eagle,player_10_R8 Revolver,player_10_Dual Berettas,player_10_Smoke Grenade,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade
0,1,5,66.7,30,58.1,G2 Esports,NiKo,0,1.0,1.0,...,0,0,0,0,1,0,1,1,0,0
1,1,5,66.7,30,58.1,G2 Esports,NiKo,0,1.0,2.0,...,0,0,0,0,1,1,1,1,0,0
2,0,5,66.7,30,58.1,G2 Esports,NiKo,0,1.0,3.0,...,0,0,0,0,1,1,0,1,0,0
3,1,5,66.7,30,58.1,G2 Esports,NiKo,0,3.0,4.0,...,0,0,0,0,1,1,0,1,0,0
4,1,5,66.7,30,58.1,G2 Esports,NiKo,0,4.0,5.0,...,0,0,0,0,1,1,1,1,0,0

In [15]:
all_new_columns = {}

for i in range(1, 11):
    if f'player_{i}_name' in df.columns:
        new_columns_df = pd.DataFrame(index=df.index)
        
        new_columns_df[f'player_{i}_rating'] = df[f'player_{i}_name'].str.lower().map(lambda x: players_stats.get(x, {}).get('Rating', 'NA'))
        new_columns_df[f'player_{i}_kills_per_round'] = df[f'player_{i}_name'].str.lower().map(lambda x: players_stats.get(x, {}).get('Kills Per Round', 'NA'))
        new_columns_df[f'player_{i}_headshots'] = df[f'player_{i}_name'].str.lower().map(lambda x: players_stats.get(x, {}).get('Headshots', 'NA'))
        new_columns_df[f'player_{i}_deaths_per_round'] = df[f'player_{i}_name'].str.lower().map(lambda x: players_stats.get(x, {}).get('Deaths Per Round', 'NA'))
        new_columns_df[f'player_{i}_rounds_contributed'] = df[f'player_{i}_name'].str.lower().map(lambda x: players_stats.get(x, {}).get('Rounds Contributed', 'NA'))
        
        all_new_columns[f'player_{i}_name'] = new_columns_df

In [16]:
for key, value in all_new_columns.items():
    insert_pos = df.columns.get_loc(key) + 1
    df = pd.concat([df.iloc[:, :insert_pos], value, df.iloc[:, insert_pos:]], axis=1)

In [17]:
df.head()

,round_winner,team_1_position,team_1_win_percentage,team_2_position,team_2_win_percentage,player_1_team_name,player_1_name,player_1_rating,player_1_kills_per_round,player_1_headshots,...,player_10_CZ75-Auto,player_10_Desert Eagle,player_10_R8 Revolver,player_10_Dual Berettas,player_10_Smoke Grenade,player_10_High Explosive Grenade,player_10_Flashbang,player_10_Incendiary Grenade,player_10_Molotov,player_10_Decoy Grenade
0,1,5,66.7,30,58.1,G2 Esports,NiKo,1.18,0.72,51.8,...,0,0,0,0,1,0,1,1,0,0
1,1,5,66.7,30,58.1,G2 Esports,NiKo,1.18,0.72,51.8,...,0,0,0,0,1,1,1,1,0,0
2,0,5,66.7,30,58.1,G2 Esports,NiKo,1.18,0.72,51.8,...,0,0,0,0,1,1,0,1,0,0
3,1,5,66.7,30,58.1,G2 Esports,NiKo,1.18,0.72,51.8,...,0,0,0,0,1,1,0,1,0,0
4,1,5,66.7,30,58.1,G2 Esports,NiKo,1.18,0.72,51.8,...,0,0,0,0,1,1,1,1,0,0

In [19]:
df.any().isna().value_counts()

False    545
Name: count, dtype: int64

In [20]:
df.to_csv('../data/cleaned_rounds_data_with_stats.csv', index=False)